"""empty message

Revision ID: 6d8f8fd12a9c
Revises: 01d74e9704d9
Create Date: 2023-09-22 11:20:05.126283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '6d8f8fd12a9c'
down_revision: Union[str, None] = '01d74e9704d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filmlike',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filmid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('filmlike')
    # ### end Alembic commands ###
